Update universalJavaApplicationStub to use public JRE if there is nothing set

diff --git a/src/main/resources/osxapp/universalJavaApplicationStub b/src/main/resources/osxapp/universalJavaApplicationStub
--- a/src/main/resources/osxapp/universalJavaApplicationStub
+++ b/src/main/resources/osxapp/universalJavaApplicationStub
@@ -230,11 +230,6 @@ elif [ ! -z ${JVMVersion} ] && [ -x /usr/libexec/java_home ] && /usr/libexec/jav
 
 	if /usr/libexec/java_home -F -v ${JVMVersion}; then
 		JAVACMD="`/usr/libexec/java_home -F -v ${JVMVersion} 2> /dev/null`/bin/java"
-	else
-		# display error message with applescript
-		osascript -e "tell application \"System Events\" to display dialog \"ERROR launching '${CFBundleName}'\n\nNo suitable Java version found on your system!\nThis program requires Java ${JVMVersion}\nMake sure you install the required Java version.\" with title \"${CFBundleName}\" buttons {\" OK \"} default button 1 with icon path to resource \"${CFBundleIconFile}\" in bundle (path to me)"
-		# exit with error
-		exit 3
 	fi
 
 # otherwise check "/usr/libexec/java_home" symlinks
@@ -244,15 +239,19 @@ elif [ -x /usr/libexec/java_home ] && /usr/libexec/java_home -F; then
 # otherwise check Java standard symlink (old Apple Java)
 elif [ -h /Library/Java/Home ]; then
 	JAVACMD="/Library/Java/Home/bin/java"
+fi
 
 # fallback: public JRE plugin (Oracle Java)
-else
+if [ -z ${JAVACMD} ]; then
 	JAVACMD="/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java"
 fi
 
-# fallback fallback: /usr/bin/java
-# but this would prompt to install deprecated Apple Java 6
-
+if [ -z ${JAVACMD} ]; then
+	# display error message with applescript
+	osascript -e "tell application \"System Events\" to display dialog \"ERROR launching '${CFBundleName}'\n\nNo suitable Java version found on your system!\nThis program requires Java ${JVMVersion}\nMake sure you install the required Java version.\" with title \"${CFBundleName}\" buttons {\" OK \"} default button 1 with icon path to resource \"${CFBundleIconFile}\" in bundle (path to me)"
+	# exit with error
+	exit 3
+fi
 
 
 
