Check the java version of the osx java we find and check that it's not 1.6

diff --git a/src/main/resources/osxapp/universalJavaApplicationStub b/src/main/resources/osxapp/universalJavaApplicationStub
--- a/src/main/resources/osxapp/universalJavaApplicationStub
+++ b/src/main/resources/osxapp/universalJavaApplicationStub
@@ -248,12 +248,28 @@ fi
 
 if [ -z ${JAVACMD} ]; then
 	# display error message with applescript
-	osascript -e "tell application \"System Events\" to display dialog \"ERROR launching '${CFBundleName}'\n\nNo suitable Java version found on your system!\nThis program requires Java ${JVMVersion}\nMake sure you install the required Java version.\" with title \"${CFBundleName}\" buttons {\" OK \"} default button 1 with icon path to resource \"${CFBundleIconFile}\" in bundle (path to me)"
+	osascript -e "tell application \"System Events\" to display dialog \"ERROR launching '${CFBundleName}'!\n\nYou need to have JAVA installed on your Mac!\nVisit http://java.com for more information...\" with title \"${CFBundleName}\" buttons {\" OK \"} default button 1 with icon path to resource \"${CFBundleIconFile}\" in bundle (path to me)"
+
+	# and open java.com
+	open http://java.com
+
 	# exit with error
 	exit 3
 fi
 
+JAVAVER = ${JAVACMD} -version 2>&1 | awk -F '"' '/version/ {print $2}' | cut -c1-3
 
+# Check the java version we're trying to use isn't 1.6
+if [ -z ${JAVAVER} ] || [ ${JAVAVER} == '1.6' ]; then
+	# display error message with applescript
+	osascript -e "tell application \"System Events\" to display dialog \"ERROR launching '${CFBundleName}'\n\nNo suitable Java version found on your system!\nThis program requires Java ${JVMVersion}\nMake sure you install the required Java version.\" with title \"${CFBundleName}\" buttons {\" OK \"} default button 1 with icon path to resource \"${CFBundleIconFile}\" in bundle (path to me)"
+
+	# and open java.com
+	open http://java.com
+
+	# exit with error
+	exit 3
+fi
 
 #
 # execute JAVA commandline and do some pre-checks
